package se.premex.exifdebug

import android.content.Context
import android.os.Build
import android.util.Log

/**
 * Guided test runner: walks the user through every picker, records results,
 * and produces a single Markdown report at the end. The report is:
 *  1. Logged to logcat under tag `ExifDebug` (for `adb logcat -s ExifDebug`).
 *  2. Shown on-screen with a Share button.
 *  3. Suitable for pasting into a GitHub issue or handing to an AI agent
 *     to reason about and turn into a PR.
 *
 * No persistence — the run is in-memory only. Tap the recorder again to
 * start over.
 */
class TestRecorder {
    /** Order matters: we walk through the list in this sequence. */
    val steps: List<PickerKind> = PickerKind.entries

    private val results = mutableMapOf<PickerKind, PickResult>()
    private var index: Int = 0
    private val deviceFacts: List<Pair<String, String>> = collectDeviceFacts()

    val currentStep: Int get() = index
    val totalSteps: Int = steps.size
    val currentPicker: PickerKind? get() = steps.getOrNull(index)
    val isComplete: Boolean get() = index >= steps.size

    fun record(result: PickResult) {
        results[result.pickerKind] = result
        // Only advance if the recorded picker matches the current step. This
        // way a stray free-mode pick mid-test doesn't skip ahead.
        if (result.pickerKind == currentPicker) index++
    }

    fun skip() {
        if (!isComplete) index++
    }

    fun reset() {
        results.clear()
        index = 0
    }

    /** Render a Markdown report safe to paste into a GitHub issue. */
    fun renderReport(): String = buildString {
        appendLine("# EXIF Picker Lab — test run")
        appendLine()
        appendLine("## Device")
        appendLine()
        appendLine("| key | value |")
        appendLine("|---|---|")
        deviceFacts.forEach { (k, v) -> appendLine("| $k | $v |") }
        appendLine()
        appendLine("## Picker × Read-method matrix")
        appendLine()
        append("| Picker |")
        ExifReadMethod.entries.forEach { append(" ${it.name} |") }
        appendLine()
        append("|---|")
        ExifReadMethod.entries.forEach { append("---|") }
        appendLine()
        for (kind in PickerKind.entries) {
            append("| ${kind.label} |")
            val r = results[kind]
            if (r == null) {
                ExifReadMethod.entries.forEach { append(" — |") }
            } else {
                ExifReadMethod.entries.forEach { method ->
                    val rr = r.readResults.firstOrNull { it.method == method }
                    val cell = when {
                        rr == null -> "—"
                        rr.latLong != null -> "✓"
                        else -> "✗"
                    }
                    append(" $cell |")
                }
            }
            appendLine()
        }
        appendLine()
        appendLine("## Per-picker details")
        for (kind in PickerKind.entries) {
            val r = results[kind] ?: continue
            appendLine()
            appendLine("### ${kind.label}")
            appendLine()
            appendLine("> ${kind.behaviour}")
            appendLine()
            appendLine("- URI: `${r.uri}`")
            appendLine("- Authority: `${r.uri.authority ?: "—"}`")
            appendLine("- MIME: `${r.mimeType ?: "—"}`")
            appendLine("- Size: ${r.sizeBytes ?: "?"} bytes")
            appendLine("- Display name: ${r.displayName ?: "—"}")
            appendLine()
            appendLine("| Read method | Status | latLong | Error |")
            appendLine("|---|---|---|---|")
            r.readResults.forEach { rr ->
                val ll = rr.latLong?.let { "${it.first}, ${it.second}" } ?: "—"
                val err = rr.error?.replace("|", "\\|")?.take(140) ?: "—"
                appendLine("| ${rr.method.label} | ${rr.status} | $ll | $err |")
            }
        }
        appendLine()
        appendLine("---")
        appendLine("Generated by EXIF Picker Lab. https://github.com/warting/exif_picker_lab")
    }

    /** Dump the report to logcat in chunks (logd has a per-line cap of ~4KB). */
    fun logReport() {
        val report = renderReport()
        Log.i(TAG, "=== TEST REPORT START ===")
        report.lineSequence().forEach { Log.i(TAG, it) }
        Log.i(TAG, "=== TEST REPORT END ===")
    }

    private fun collectDeviceFacts(): List<Pair<String, String>> = listOf(
        "manufacturer" to Build.MANUFACTURER,
        "model" to Build.MODEL,
        "device" to Build.DEVICE,
        "fingerprint" to Build.FINGERPRINT,
        "android.version" to Build.VERSION.RELEASE,
        "android.sdkInt" to Build.VERSION.SDK_INT.toString(),
    )

    companion object { private const val TAG = "ExifDebug" }
}
